### ISSUE TITLE
Segmentation fault gulp jest

### ISSUE THREAD

**Issue by bit-dragon** [alansouzati/gulp-jest#17]
I'm getting the follow exception when I run `gulp jest` task, It's a little weird cause the first time when I created the test and I run the command It was working correctly.

Any ideas?

**Comment by eudisd** [comment]
This is happening with me as well.  When I try to require a package inside a jest `it` block it errors out and segfaults:

```bash
❯ gulp jest                                                                                          ⏎
[18:10:05] Using gulpfile ~/github/airtime/boba/gulpfile.js
[18:10:05] Starting 'jest'...
Waiting on 1 test...[1]    54192 segmentation fault  gulp jest
```

and my gulp config is extremely straight forward:

```javascript
gulp.task('jest', function () {
  'use strict';

  return gulp
    .src(['tests'])
    .pipe(jest({
      scriptPreprocessor: './../config/jest/preprocessor.js',
      testDirectoryName: 'unit',
      testPathIgnorePatterns: [
        'node_modules'
      ],
      unmockedModulePathPatterns: ['react']
    }));
});
```

**Comment by gmjorge** [comment]
@eudisd It seems that is an issue related to this one https://github.com/facebook/jest/issues/243 so you should use node v.0.10.

Cheers!

**Comment by alansouzati** [comment]
I believe this is not an issue anymore with gulp-jest 0.5.2
