### ISSUE TITLE
Jest 0.5.0 requires iojs

### ISSUE THREAD

**Issue by screendriver** [alansouzati/gulp-jest#19]
The latest version of Jest, `0.5.0`, [requires](https://github.com/facebook/jest/blob/v0.5.0/CHANGELOG.md) iojs.

**Comment by ShayanZafar** [comment]
There is a repository called gulp-jest-jsio which is a fork of this one. They have already done the integration for this? Would it make sense to re-use their implementation of this integration to prevent multiple repositories diverging from the original gulp integration?

Here are the links to the repo and page:

https://www.npmjs.com/package/gulp-jest-iojs
https://github.com/binarykitchen/gulp-jest-iojs

**Comment by alansouzati** [comment]
I've updated gulp-jest to use Jest 15.0.0
