### ISSUE TITLE
Remove use of React.tools to remove warnings

### ISSUE THREAD

**Issue by lemiii** [alansouzati/gulp-jest#23]
React.tools makes use of an undocumented feature - `React.__spread`. Error started popping up in React v15.0.0 when they removed this undocumented api. It was added back in [v15.0.1](http://facebook.github.io/react/blog/2016/04/08/react-v15.0.1.html) with a depreciation warning.

Since [react-tools](https://www.npmjs.com/package/react-tools) is no longer supported, please switch to something else such as [babel](http://github.com/babel/babel).

See facebook/react/pull/6444 for details

**Comment by alansouzati** [comment]
done
