### ISSUE TITLE
How to use CLI parameter

### ISSUE THREAD

**Issue by eskimoblood** [alansouzati/gulp-jest#26]
How can I pass the CLI parameter to the task, aka `-u` `--no-cache` and so on.

**Comment by alansouzati** [comment]
Gulp-jest does not use the cli at all. So you would need to map it to the object key in the Jest API.

For example `-u` maps to `updateSnapshot`

See this file for reference:

https://github.com/grommet/grommet-toolbox/blob/master/src/gulp-tasks-test.js#L55
