### ISSUE TITLE
Gulp exists without errors even if a test suite fails.

### ISSUE THREAD

**Issue by boljen** [alansouzati/gulp-jest#28]
In my specific case the test failed because the preprocessor caused an error rather than the actual test code itself.

As it turns out, in some cases a failure is considered a "failed test suite" rather than a "failed test", and these are reported separately.

To fix this, replace [this line](https://github.com/alansouzati/gulp-jest/blob/master/src/index.js#L14
) with:

    if(result.numFailedTests || result.numFailedTestSuites) {

**Comment by alansouzati** [comment]
are you up to send a pull request to fix this @boljen ?

Thanks for identifying the issue.
