### ISSUE TITLE
Update to Jest 20

### ISSUE THREAD

**Issue by ai** [alansouzati/gulp-jest#35]
@alansouzati Jest 20 was released and we need to update this module to support new version.

**Comment by ai** [comment]
Any updates?

**Comment by alansouzati** [comment]
let me look into this. Sorry but I'm really busy at work and I'm not sure when I will have time to stop and take a look on it.

**Comment by Fulkman** [comment]
I have send PR https://github.com/alansouzati/gulp-jest/pull/36 with small change. Hope that is all what needs to be done.

**Comment by alansouzati** [comment]
Let me review this today. I will release a new version after that. Thanks for your contribution

**Comment by alansouzati** [comment]
gulp-jest 2.0.0 released with support for Jest 20. Thank you guys.

**Comment by alansouzati** [comment]
FYI. basic support is there but it still "fails" when you want a specific config. Like sending `updateSnapshot: true`. I will fix this.

**Comment by alansouzati** [comment]
Good news, just remove `config: {}` object. now it is flat structure. I've updated the README accordingly.

https://github.com/alansouzati/gulp-jest#usage
