### ISSUE TITLE
Gulp-jest doesn't support jest 21

### ISSUE THREAD

**Issue by Anthony-Mckale** [alansouzati/gulp-jest#41]
Hi guys,

Seems the _jestCli2.default.runCLI function parameters have changed between v2 and v3

as such passed config options aren't be passed along

{code}
    "jest": "^21.1.0",
    "jest-cli": "^21.1.0",
    "gulp-jest": "^2.0.0",
{code}

looks like options needs to be a array maybe ?

Only had a small look but looks like a small issue to solve, of course working out may need some knowledge of which jest version it's trying to run

cheers

Anthony

**Comment by sergey-su** [comment]
gulp-jest passes config as an object in field options.config. In ver 21 JestCLI expects config to be a string. See https://github.com/facebook/jest/blob/master/types/Argv.js field config. 
More specifically options.config should be json string.

**Comment by alansouzati** [comment]
FIxed in https://github.com/alansouzati/gulp-jest/releases/tag/v3.0.0
