### ISSUE TITLE
Could you release the latest commit?

### ISSUE THREAD

**Issue by joybro** [alansouzati/gulp-jest#57]
Hi,

I ran into this code coverage failure issue(#33) and found that it's patched but not released yet. Could you release the latest commit so that people can use it?

Thanks,
Young

**Comment by aarontrank** [comment]
Hey @alansouzati!  Thanks for your maintaining this repo.... echoing the comment above.  Would it be possible for your to release the latest commit and publish to NPM?  That would be SUPER helpful!!

**Comment by alansouzati** [comment]
doing that now. Sorry I've sort of abandoned open source. I was feeling super burned out. I'm happy to transfer this project to you for future releases/reviews. ping me if you want me to transfer that to you.

**Comment by alansouzati** [comment]
4.0.3 released

**Comment by aarontrank** [comment]
Thanks!  I definitely can relate to the Open source burnout.  That said, if
you’d like to transfer it to me I’d be happy to take it on.

**Comment by alansouzati** [comment]
done

**Comment by alansouzati** [comment]
I will add you on NPM too so that you can publish

**Comment by aarontrank** [comment]
Awesome!  Glad to help.  Is there anything that needs to be done from the
NPM side of things?

**Comment by alansouzati** [comment]
yeah it turns out I can't add you to the NPM collab end. please reach out to https://www.npmjs.com/~dakuan

**Comment by aarontrank** [comment]
Will do :)
