### ISSUE TITLE
Add support for jest CLI options

### ISSUE THREAD

**Issue by ncuillery** [alansouzati/gulp-jest#7]
Hi,

Is there a reason to not support the helpful jest CLI options (like `runInBand`, `maxWorkers`, `coverage`) ?

It would be great if we can provide arguments to CLI via the task config or the `process.argv`. What your feeling about that ?

I can do a PR.

**Comment by Dakuan** [comment]
hello! I think it was because they weren't available when I wrote the plugin :)

Do feel free to add them

**Comment by alansouzati** [comment]
Fixed.
